//! Negative auth tests for entrypoints that call `require_auth()` (issue #38).
//!
//! Auth bugs are common: an entrypoint that means to gate a mutation behind
//! `require_auth()` but checks the wrong address (or checks it under the
//! wrong condition) will accept calls it shouldn't. Every entrypoint whose
//! body calls `.require_auth()` gets one test proving the opposite
//! direction: called through `try_*` with no auths mocked, it must come back
//! `Err` rather than succeeding or panicking with an unrelated error.
//!
//! Detection is on the source text (see
//! [`crate::detect::find_require_auth_methods`]) rather than the contract's
//! actual authorization tree, so it cannot tell *which* address is checked —
//! only that some `.require_auth()` call exists in the method body. That is
//! enough for a meaningful test: an `Env` built without `mock_all_auths` has
//! no authorizations at all, so any `require_auth()` call the entrypoint
//! makes fails regardless of which address it is on.

use crate::detect::{ContractInfo, MethodInfo};
use crate::to_snake_case;
use soroban_forge_core::render::{render_str, Vars};

/// Header of the generated negative-auth test file.
pub const NEGATIVE_AUTH_TEST_RS: &str = r#"//! Generated by `soroban-forge test-init`. Negative auth tests.
//!
//! Every entrypoint below calls `require_auth()` somewhere in its body. Each
//! test builds an `Env` with no auths mocked (unlike `common::test_env()`)
//! and calls the entrypoint through `try_*`, asserting the call is rejected.
//!
//! A failure here means the entrypoint succeeded (or panicked with something
//! other than an auth error) despite no address having authorized the call —
//! a real authorization bug, not a flaky test. If the contract's constructor
//! itself calls `require_auth()`, `env.register(...)` below may need auths
//! mocked for registration to succeed at all; add `env.mock_all_auths()`
//! before registration in that case — registration is not what this test
//! exercises.

mod common;
"#;

/// One negative-auth test. Receives `contract_type`, `fn_name`,
/// `contract_args`, `entrypoint` and `entrypoint_args`.
pub const NEGATIVE_AUTH_TEST_FN: &str = r#"
#[test]
fn {{fn_name}}_{{entrypoint}}_rejects_without_auth() {
    let env = soroban_sdk::Env::default();
    let contract_id = env.register({{contract_type}}, {{contract_args}});
    let client = {{contract_type}}Client::new(&env, &contract_id);

    let result = client.try_{{entrypoint}}({{entrypoint_args}});
    assert!(
        result.is_err(),
        "`{{entrypoint}}` calls require_auth() but the call succeeded without any authorization mocked"
    );
}
"#;

/// Builds the call argument list for `method`, using
/// [`crate::detect::map_type_to_default`] for each parameter. Soroban clients
/// take arguments by reference. `Address`-typed defaults come from
/// `Address::generate` (via `common::new_account`), which — unlike
/// `require_auth` — needs no authorization, so building these arguments does
/// not itself mock anything.
fn call_args(method: &MethodInfo) -> String {
    method
        .args
        .iter()
        .map(|(_, ty)| format!("&{}", crate::detect::map_type_to_default(ty)))
        .collect::<Vec<_>>()
        .join(", ")
}

/// Render `tests/forge_negative_auth.rs`. Returns an empty string when no
/// entrypoint calls `require_auth()`, so the file is only written for
/// contracts it says something about.
pub fn build_negative_auth_tests(info: &ContractInfo) -> String {
    if info.auth_required_methods.is_empty() {
        return String::new();
    }

    let mut out = String::from(NEGATIVE_AUTH_TEST_RS);
    out.push_str(&format!(
        "use {}::{{ {} }};\n",
        info.crate_name,
        info.contract_types
            .iter()
            .flat_map(|ct| [ct.clone(), format!("{ct}Client")])
            .collect::<Vec<_>>()
            .join(", ")
    ));

    for contract_type in &info.contract_types {
        for method in &info.auth_required_methods {
            let mut vars = Vars::new();
            vars.insert("contract_type".into(), contract_type.clone());
            vars.insert("fn_name".into(), to_snake_case(contract_type));
            vars.insert("contract_args".into(), info.constructor_args.clone());
            vars.insert("entrypoint".into(), method.name.clone());
            vars.insert("entrypoint_args".into(), call_args(method));
            out.push_str(&render_str(NEGATIVE_AUTH_TEST_FN, &vars));
        }
    }

    out
}

#[cfg(test)]
mod tests {
    use super::*;

    fn method(name: &str, args: &[(&str, &str)]) -> MethodInfo {
        MethodInfo {
            name: name.to_string(),
            args: args
                .iter()
                .map(|(n, t)| (n.to_string(), t.to_string()))
                .collect(),
        }
    }

    fn info_with_auth_methods(methods: Vec<MethodInfo>) -> ContractInfo {
        ContractInfo {
            package_name: "demo".into(),
            crate_name: "demo".into(),
            contract_types: vec!["Demo".into()],
            has_constructor: false,
            has_testutils: true,
            constructor_args: "()".into(),
            has_proptest: true,
            methods: methods.clone(),
            constructor_arg_types: None,
            events: vec![],
            has_contractevent: false,
            has_token_deps: false,
            token_param_names: vec![],
            init_method: None,
            has_persistent_storage: false,
            has_instance_storage: false,
            has_temporary_storage: false,
            auth_required_methods: methods,
        }
    }

    #[test]
    fn build_negative_auth_tests_empty_without_require_auth() {
        let info = info_with_auth_methods(vec![]);
        assert!(build_negative_auth_tests(&info).is_empty());
    }

    #[test]
    fn build_negative_auth_tests_generates_one_test_per_method() {
        let methods = vec![
            method("mint", &[("to", "Address"), ("amount", "i128")]),
            method("burn", &[("from", "Address"), ("amount", "i128")]),
        ];
        let info = info_with_auth_methods(methods);
        let out = build_negative_auth_tests(&info);

        assert!(out.contains("mod common;"));
        assert!(out.contains("use demo::{ Demo, DemoClient };"));
        assert!(out.contains("fn demo_mint_rejects_without_auth()"));
        assert!(out.contains("fn demo_burn_rejects_without_auth()"));
        assert!(out.contains("let env = soroban_sdk::Env::default();"));
        assert!(out.contains("client.try_mint(&common::new_account(&env), &0_i128)"));
        assert!(out.contains("result.is_err()"));
        assert!(!out.contains("{{"));
    }

    #[test]
    fn call_args_uses_defaults_for_every_parameter() {
        let m = method(
            "transfer",
            &[("from", "Address"), ("to", "Address"), ("amount", "i128")],
        );
        let rendered = call_args(&m);
        assert_eq!(
            rendered,
            "&common::new_account(&env), &common::new_account(&env), &0_i128"
        );
    }
}