//! i128 arithmetic overflow tests (issue #101).
//!
//! Soroban balances, amounts and most contract-level numeric state use
//! `i128`. This module detects entrypoints that take an `i128` argument and
//! generates a test per detected argument that calls the entrypoint with a
//! large value near `i128::MAX` / `i128::MIN` — quartered, so a single
//! addition, multiplication-by-a-small-constant or doubling inside the
//! contract still has headroom rather than being guaranteed to overflow no
//! matter what the contract does with it.
//!
//! Detection is on the argument type alone (as with the container-round-trip
//! tests in `containers.rs`): `MethodInfo` carries no function body or return
//! type, so there is no way to see the contract's actual arithmetic. The
//! generated tests are therefore black-box: they exercise the entrypoint with
//! a large `i128` and rely on Rust's overflow checks catching a silent
//! wraparound as a panic. Cargo's default `dev` profile — the one `cargo
//! test` builds against — already sets `overflow-checks = true`, so no
//! additional profile configuration is required for these tests to do their
//! job.
//!
//! A failing test here is a real finding: the contract's arithmetic overflowed
//! (or underflowed) on a value that was still within `i128`'s own range. Fix
//! it with checked/saturating arithmetic, or narrow the literal if the value
//! is genuinely outside what the contract is meant to support.

use crate::detect::{ContractInfo, MethodInfo};
use crate::to_snake_case;
use soroban_forge_core::render::{render_str, Vars};

/// Header of the generated overflow test file.
pub const OVERFLOW_TEST_RS: &str = r#"//! Generated by `soroban-forge test-init`. i128 arithmetic overflow tests.
//!
//! Soroban balances and amounts are typically `i128`. Each test below calls
//! one detected i128-taking entrypoint with a large value near `i128::MAX` /
//! `i128::MIN` (quartered, to leave headroom for a single doubling or
//! addition inside the contract) and relies on the `overflow-checks = true`
//! default of cargo's `dev` profile to turn a silent wraparound into a
//! panicking test failure.
//!
//! A test failing here is a real finding: the contract's arithmetic
//! overflowed a value that was still within `i128`'s own range. Guard it with
//! checked/saturating operations, or narrow the literal below if the value
//! genuinely exceeds what the contract is meant to handle.

mod common;
"#;

/// One overflow test. Receives `contract_type`, `fn_name`, `entrypoint`,
/// `arg_name`, `case`, `literal` and `call_args`.
pub const OVERFLOW_TEST_FN: &str = r#"
#[test]
fn {{fn_name}}_{{entrypoint}}_handles_{{case}}_{{arg_name}}() {
    let env = common::test_env();
    let contract_id = env.register({{contract_type}}, {{contract_args}});
    let client = {{contract_type}}Client::new(&env, &contract_id);

    let {{arg_name}}_value: i128 = {{literal}};
    let _ = client.{{entrypoint}}({{call_args}});
}
"#;

/// An `i128`-typed argument found on an entrypoint.
#[derive(Debug, Clone, PartialEq)]
pub struct I128Arg {
    /// Entrypoint the argument belongs to.
    pub method: String,
    /// Argument name, e.g. `amount`.
    pub name: String,
    /// Zero-based position in the method's argument list.
    pub position: usize,
}

/// Strips references and lifetimes so `&i128` and `&'a i128` still match.
fn normalize(ty: &str) -> String {
    ty.replace('&', "")
        .replace("'a", "")
        .replace("mut ", "")
        .trim()
        .to_string()
}

/// True when `ty` is (a possibly-referenced) `i128`.
fn is_i128(ty: &str) -> bool {
    normalize(ty) == "i128"
}

/// Finds every `i128` argument across the contract's entrypoints.
pub fn find_i128_args(methods: &[MethodInfo]) -> Vec<I128Arg> {
    let mut found = Vec::new();
    for method in methods {
        // `__constructor` runs at registration, not through the client, so it
        // cannot be exercised the way an entrypoint can.
        if method.name == "__constructor" {
            continue;
        }
        for (position, (name, ty)) in method.args.iter().enumerate() {
            if is_i128(ty) {
                found.push(I128Arg {
                    method: method.name.clone(),
                    name: name.clone(),
                    position,
                });
            }
        }
    }
    found
}

/// The two boundary cases every detected `i128` argument is exercised with.
const CASES: [&str; 2] = ["large_positive", "large_negative"];

/// The literal expression for `case`. Quartered from the true `i128::MAX` /
/// `i128::MIN` so a single addition or doubling inside the contract has
/// headroom, per [`CASES`]'s doc comment.
fn literal(case: &str) -> String {
    match case {
        "large_positive" => "i128::MAX / 4".to_string(),
        _ => "i128::MIN / 4".to_string(),
    }
}

/// Builds the call argument list, substituting the boundary value at
/// `arg.position` and defaults elsewhere. Soroban clients take arguments by
/// reference, hence the `&` on each.
fn call_args(method: &MethodInfo, arg: &I128Arg, binding_name: &str) -> String {
    method
        .args
        .iter()
        .enumerate()
        .map(|(i, (_, ty))| {
            if i == arg.position {
                format!("&{binding_name}")
            } else {
                format!("&{}", crate::detect::map_type_to_default(ty))
            }
        })
        .collect::<Vec<_>>()
        .join(", ")
}

/// Render `tests/forge_overflow.rs`. Returns an empty string when no
/// entrypoint takes an `i128` argument, so the file is only written for
/// contracts it says something about.
pub fn build_overflow_tests(info: &ContractInfo) -> String {
    let args = find_i128_args(&info.methods);
    if args.is_empty() {
        return String::new();
    }

    let mut out = String::from(OVERFLOW_TEST_RS);
    out.push_str(&format!(
        "use {}::{{ {} }};\n",
        info.crate_name,
        info.contract_types
            .iter()
            .flat_map(|ct| [ct.clone(), format!("{ct}Client")])
            .collect::<Vec<_>>()
            .join(", ")
    ));

    for contract_type in &info.contract_types {
        for arg in &args {
            let Some(method) = info.methods.iter().find(|m| m.name == arg.method) else {
                continue;
            };

            for case in CASES {
                let binding_name = format!("{}_value", arg.name);

                let mut vars = Vars::new();
                vars.insert("contract_type".into(), contract_type.clone());
                vars.insert("fn_name".into(), to_snake_case(contract_type));
                vars.insert("contract_args".into(), info.constructor_args.clone());
                vars.insert("entrypoint".into(), arg.method.clone());
                vars.insert("arg_name".into(), arg.name.clone());
                vars.insert("case".into(), case.to_string());
                vars.insert("literal".into(), literal(case));
                vars.insert("call_args".into(), call_args(method, arg, &binding_name));
                out.push_str(&render_str(OVERFLOW_TEST_FN, &vars));
            }
        }
    }

    out
}

#[cfg(test)]
mod tests {
    use super::*;

    fn method(name: &str, args: &[(&str, &str)]) -> MethodInfo {
        MethodInfo {
            name: name.to_string(),
            args: args
                .iter()
                .map(|(n, t)| (n.to_string(), t.to_string()))
                .collect(),
        }
    }

    #[test]
    fn finds_i128_args_and_skips_the_constructor() {
        let methods = vec![
            method("__constructor", &[("initial_supply", "i128")]),
            method("mint", &[("to", "Address"), ("amount", "i128")]),
            method("noop", &[("n", "u32")]),
        ];
        let found = find_i128_args(&methods);
        assert_eq!(found.len(), 1);
        assert_eq!(found[0].method, "mint");
        assert_eq!(found[0].name, "amount");
        assert_eq!(found[0].position, 1);
    }

    #[test]
    fn matches_referenced_and_lifetimed_i128() {
        let methods = vec![method("mint", &[("amount", "&'a i128")])];
        let found = find_i128_args(&methods);
        assert_eq!(found.len(), 1);
    }

    #[test]
    fn ignores_non_i128_numeric_types() {
        let methods = vec![method("mint", &[("amount", "u128"), ("n", "i64")])];
        assert!(find_i128_args(&methods).is_empty());
    }

    #[test]
    fn finds_multiple_i128_args_on_one_entrypoint() {
        let methods = vec![method(
            "swap",
            &[("amount_in", "i128"), ("min_out", "i128")],
        )];
        let found = find_i128_args(&methods);
        assert_eq!(found.len(), 2);
        assert_eq!(found[0].name, "amount_in");
        assert_eq!(found[1].name, "min_out");
    }

    #[test]
    fn literal_values_are_quartered_bounds() {
        assert_eq!(literal("large_positive"), "i128::MAX / 4");
        assert_eq!(literal("large_negative"), "i128::MIN / 4");
    }

    #[test]
    fn call_args_substitutes_only_the_i128_position() {
        let m = method("mint", &[("to", "Address"), ("amount", "i128")]);
        let arg = I128Arg {
            method: "mint".into(),
            name: "amount".into(),
            position: 1,
        };
        let rendered = call_args(&m, &arg, "amount_value");
        assert_eq!(rendered, "&common::new_account(&env), &amount_value");
    }

    #[test]
    fn build_overflow_tests_empty_without_i128_args() {
        let info = ContractInfo {
            package_name: "demo".into(),
            crate_name: "demo".into(),
            contract_types: vec!["Demo".into()],
            has_constructor: false,
            has_testutils: true,
            constructor_args: "()".into(),
            has_proptest: true,
            methods: vec![method("noop", &[("n", "u32")])],
            constructor_arg_types: None,
            events: vec![],
            has_contractevent: false,
            has_token_deps: false,
            token_param_names: vec![],
            init_method: None,
            has_persistent_storage: false,
            has_instance_storage: false,
            has_temporary_storage: false,
        };
        assert!(build_overflow_tests(&info).is_empty());
    }

    #[test]
    fn build_overflow_tests_generates_both_cases() {
        let info = ContractInfo {
            package_name: "demo".into(),
            crate_name: "demo".into(),
            contract_types: vec!["Demo".into()],
            has_constructor: false,
            has_testutils: true,
            constructor_args: "()".into(),
            has_proptest: true,
            methods: vec![method("mint", &[("to", "Address"), ("amount", "i128")])],
            constructor_arg_types: None,
            events: vec![],
            has_contractevent: false,
            has_token_deps: false,
            token_param_names: vec![],
            init_method: None,
            has_persistent_storage: false,
            has_instance_storage: false,
            has_temporary_storage: false,
        };
        let out = build_overflow_tests(&info);

        assert!(out.contains("mod common;"));
        assert!(out.contains("use demo::{ Demo, DemoClient };"));
        assert!(out.contains("fn demo_mint_handles_large_positive_amount()"));
        assert!(out.contains("fn demo_mint_handles_large_negative_amount()"));
        assert!(out.contains("let amount_value: i128 = i128::MAX / 4;"));
        assert!(out.contains("let amount_value: i128 = i128::MIN / 4;"));
        assert!(out.contains("client.mint(&common::new_account(&env), &amount_value);"));
        assert!(!out.contains("{{"));
    }

    #[test]
    fn build_overflow_tests_covers_every_i128_arg_independently() {
        let info = ContractInfo {
            package_name: "demo".into(),
            crate_name: "demo".into(),
            contract_types: vec!["Demo".into()],
            has_constructor: false,
            has_testutils: true,
            constructor_args: "()".into(),
            has_proptest: true,
            methods: vec![method(
                "swap",
                &[("amount_in", "i128"), ("min_out", "i128")],
            )],
            constructor_arg_types: None,
            events: vec![],
            has_contractevent: false,
            has_token_deps: false,
            token_param_names: vec![],
            init_method: None,
            has_persistent_storage: false,
            has_instance_storage: false,
            has_temporary_storage: false,
        };
        let out = build_overflow_tests(&info);

        assert!(out.contains("fn demo_swap_handles_large_positive_amount_in()"));
        assert!(out.contains("fn demo_swap_handles_large_negative_amount_in()"));
        assert!(out.contains("fn demo_swap_handles_large_positive_min_out()"));
        assert!(out.contains("fn demo_swap_handles_large_negative_min_out()"));
    }
}